# Generated by Django 2.1.1 on 2018-09-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('post_title', models.CharField(max_length=50)),
                ('post_content', models.CharField(max_length=5000)),
            ],
        ),
    ]
