# Generated by Django 2.0.7 on 2018-09-05 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.PositiveSmallIntegerField()),
                ('position_y', models.PositiveSmallIntegerField()),
                ('partie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mines', to='CMS.Partie')),
            ],
        ),
    ]
