# Generated by Django 2.1.1 on 2018-09-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0002_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture_url',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
